version: '3.0'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./:/var/www/wishlist
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - app
        container_name: nginx


    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/wishlist
        container_name: app
