version: '3.0'

services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        environment:
            - NGINX_HOST=wishlist.fgislk.com
            - NGINX_PORT=80
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: app

#    database:
#        image: postgres:16.3
#        restart: always
#        shm_size: 128mb
#        volumes:
#            - ./tmp/db:/var/lib/postgresql
#        environment:
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: root
#            POSTGRES_DB: test_db
#        ports:
#            - "8001:5432"
#        container_name: pgsql
